---
services:
  web:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./html:/var/www/html
      - ./certs:/etc/ssl/certs
      #- /mnt/s/JobFiles:/mnt/s/JobFiles
      - ./logs:/var/log/apache2
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      # LDAP Configuration
      - LDAP_URL=${LDAP_URL}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
      - LDAP_GROUP=${LDAP_GROUP}
      # SSL Configuration
      - SSL_CERT_FILE=${SSL_CERT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
      - MAIN_SSL_CERT_FILE=${MAIN_SSL_CERT_FILE}
      - MAIN_SSL_KEY_FILE=${MAIN_SSL_KEY_FILE}
    restart: always
